app:
  name: "War Ticker"
  port: 8000
  env: "development"
  secret: "lorem_ipsum_dolor_si_amet_2077"

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  name: "war_ticket_dev"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  idle: 10
  max: 25
  lifetime: 60


redis:
  host: "localhost"
  port: 6379
  db: 0
