app:
  name: "War Ticker"
  port: 8000
  env: "development"

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  name: "war_ticket_dev"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"


redis:
  host: "localhost"
  port: 6379
  db: 0
