app:
  name: "War Ticker"
  port: 8000
  env: "development"

database:
  host: "localhost"
  port: 5432
  user: "root"
  password: ""
  name: "war_ticker_development"

redis:
  host: "localhost"
  port: 6379
  db: 0
